package main

//go:generate swag init

import (
	"context"
	"errors"
	"flag"
	"homelab/assets"
	"homelab/pkg/common"
	"homelab/pkg/controllers"
	"homelab/pkg/services/intelligence"
	"homelab/pkg/services/ip"
	"homelab/pkg/services/site"
	"io/fs"
	"log"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	_ "homelab/docs" // This will be generated by swag
	"homelab/pkg/services/actions"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/google/uuid"
	"github.com/spf13/afero"
	httpSwagger "github.com/swaggo/http-swagger"
	"gopkg.d7z.net/middleware/kv"
	"gopkg.d7z.net/middleware/lock"
	"gopkg.in/yaml.v3"
)

var (
	config string
	debug  bool
)

func init() {
	flag.StringVar(&config, "config", "", "config file")
	flag.BoolVar(&debug, "debug", false, "debug mode")
	flag.Parse()
}

// @title Homelab API
// @version 1.0
// @description This is a sample server for homelab.
// @BasePath /api/v1
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	if config != "" {
		if data, err := os.ReadFile(config); err == nil {
			if err = yaml.Unmarshal(data, common.Opts); err != nil {
				log.Fatal(err)
			}
		} else {
			log.Fatal("config file not exist")
		}
	}
	common.Opts.ParseEnv()
	db, err := kv.NewKVFromURL(common.Opts.DB)
	if err != nil {
		log.Fatal(err)
	}
	common.DB = db
	defer db.Close()

	locker, err := lock.NewLocker(common.Opts.Lock)
	if err != nil {
		log.Fatalf("Failed to initialize locker: %v", err)
	}
	common.Locker = locker

	// Initialize VFS (User Data)
	vfs, err := common.InitVFS(common.Opts.VFS)
	if err != nil {
		log.Fatalf("Failed to initialize VFS: %v", err)
	}
	common.FS = vfs

	// Initialize Temp FS (Task Workspaces)
	tempFs, err := common.InitVFS(common.Opts.TempDir)
	if err != nil {
		log.Fatalf("Failed to initialize Temp FS: %v", err)
	}
	common.TempDir = tempFs

	// Smoke test VFS: write and delete a random file
	testFile := ".homelab_vfs_test_" + uuid.New().String()
	if err := afero.WriteFile(common.FS, testFile, []byte("ok"), 0644); err != nil {
		log.Fatalf("VFS smoke test failed (write): %v", err)
	}
	_ = common.FS.Remove(testFile)

	// Smoke test Temp FS
	if err := afero.WriteFile(common.TempDir, testFile, []byte("ok"), 0644); err != nil {
		log.Fatalf("Temp FS smoke test failed (write): %v", err)
	}
	_ = common.TempDir.Remove(testFile)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Initialize Actions Scoped FS
	actions.Init()
	// Initialize IP Services
	mmdbManager := ip.NewMMDBManager()
	ipPoolService := ip.NewIPPoolService(mmdbManager)
	analysisEngine := ip.NewAnalysisEngine(mmdbManager)
	exportManager := ip.NewExportManager(analysisEngine)
	exportManager.StartCleanupTimer()
	ipPoolService.SetExportManager(exportManager)
	ipPoolService.SetAnalysisEngine(analysisEngine)
	controllers.InitIPControllers(ipPoolService, analysisEngine, exportManager)
	ipPoolService.StartSyncRunner(context.Background())
	// Initialize Site Services
	siteAnalysisEngine := site.NewAnalysisEngine(mmdbManager)
	sitePoolService := site.NewSitePoolService(siteAnalysisEngine)
	siteExportManager := site.NewExportManager(siteAnalysisEngine)
	siteExportManager.StartCleanupTimer()
	sitePoolService.SetExportManager(siteExportManager)
	controllers.InitSiteControllers(sitePoolService, siteAnalysisEngine, siteExportManager)
	site.RegisterSiteProcessors(sitePoolService)
	intelligenceService := intelligence.NewIntelligenceService(mmdbManager)
	if err := intelligenceService.Init(ctx); err != nil {
		log.Printf("Failed to initialize intelligence service: %v", err)
	}
	controllers.InitIntelligenceControllers(intelligenceService)

	actions.BootUpSelfHealing()
	if err := actions.GlobalTriggerManager.InitTriggers(ctx); err != nil {
		log.Printf("Failed to initialize triggers: %v", err)
	}
	actions.GlobalTriggerManager.Start()

	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			defer func() {
				if rvr := recover(); rvr != nil {
					if rvr == http.ErrAbortHandler {
						panic(rvr)
					}
					log.Printf("Panic: %v", rvr)
					common.InternalServerError(w, r, http.StatusInternalServerError, "Internal Server Error")
				}
			}()
			next.ServeHTTP(w, r)
		})
	})

	r.Group(func(r chi.Router) {
		r.Use(middleware.Logger)
		Router(r)
	})

	r.Get("/api/swagger", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/api/swagger/", http.StatusMovedPermanently)
	})
	r.Mount("/api/swagger", httpSwagger.Handler(
		httpSwagger.URL("/api/swagger/doc.json"),
	))

	if debug {
		target, _ := url.Parse("http://127.0.0.1:4200")
		proxy := httputil.NewSingleHostReverseProxy(target)
		r.NotFound(func(w http.ResponseWriter, r *http.Request) {
			proxy.ServeHTTP(w, r)
		})
	} else {
		staticFS, err := fs.Sub(assets.Static, "static")
		if err != nil {
			log.Fatal(err)
		}
		fileServer := http.FileServer(http.FS(staticFS))
		r.NotFound(func(w http.ResponseWriter, r *http.Request) {
			path := strings.TrimPrefix(r.URL.Path, "/")
			if path == "" {
				path = "index.html"
			}
			_, err := staticFS.Open(path)
			if err != nil {
				r.URL.Path = "/"
			}
			fileServer.ServeHTTP(w, r)
		})
	}

	srv := &http.Server{
		Addr:    common.Opts.Bind,
		Handler: r,
	}

	go func() {
		log.Printf("Server starting on %s", common.Opts.Bind)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("listen: %s\n", err)
		}
	}()

	<-ctx.Done()

	log.Println("Shutting down server...")
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("Server forced to shutdown: %v", err)
	}
	log.Println("Server exiting")
}
