package main

//go:generate swag init

import (
	"context"
	"errors"
	"flag"
	"homelab/assets"
	"homelab/pkg/common"
	runtimepkg "homelab/pkg/runtime"

	intrepo "homelab/pkg/repositories/network/intelligence"
	"io/fs"
	"log"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	_ "homelab/docs" // This will be generated by swag

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/render"
	"github.com/google/uuid"
	"github.com/spf13/afero"
	httpSwagger "github.com/swaggo/http-swagger"
	"gopkg.d7z.net/middleware/kv"
	"gopkg.d7z.net/middleware/lock"
	queuepkg "gopkg.d7z.net/middleware/queue"
	"gopkg.d7z.net/middleware/subscribe"
	"gopkg.in/yaml.v3"
)

var (
	config string
	debug  bool
)

func init() {
	flag.StringVar(&config, "config", "", "config file")
	flag.BoolVar(&debug, "debug", false, "debug mode")
}

// @title Homelab API
// @version 1.0
// @description This is a sample server for homelab.
// @BasePath /api/v1
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	if !flag.Parsed() {
		flag.Parse()
	}
	if config != "" {
		if data, err := os.ReadFile(config); err == nil {
			if err = yaml.Unmarshal(data, common.Opts); err != nil {
				log.Fatal(err)
			}
		} else {
			log.Fatal("config file not exist")
		}
	}
	common.Opts.ParseEnv()
	db, err := kv.NewKVFromURL(common.Opts.DB)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	locker, err := lock.NewLocker(common.Opts.Lock)
	if err != nil {
		log.Fatalf("Failed to initialize locker: %v", err)
	}

	taskQueue, err := queuepkg.NewQueueFromURL(common.Opts.Queue)
	if err != nil {
		log.Fatalf("Failed to initialize queue: %v", err)
	}
	defer taskQueue.Close()

	subscriber, err := subscribe.NewSubscriberFromURL(common.Opts.PubSub)
	if err != nil {
		log.Fatalf("Failed to initialize subscriber: %v", err)
	}

	// Initialize VFS (User Data)
	vfs, err := common.InitVFS(common.Opts.VFS)
	if err != nil {
		log.Fatalf("Failed to initialize VFS: %v", err)
	}

	// Initialize Temp FS (Task Workspaces)
	tempFs, err := common.InitVFS(common.Opts.TempDir)
	if err != nil {
		log.Fatalf("Failed to initialize Temp FS: %v", err)
	}

	// Smoke test VFS: write and delete a random file
	testFile := ".homelab_vfs_test_" + uuid.New().String()
	if err := afero.WriteFile(vfs, testFile, []byte("ok"), 0644); err != nil {
		log.Fatalf("VFS smoke test failed (write): %v", err)
	}
	_ = vfs.Remove(testFile)

	// Smoke test Temp FS
	if err := afero.WriteFile(tempFs, testFile, []byte("ok"), 0644); err != nil {
		log.Fatalf("Temp FS smoke test failed (write): %v", err)
	}
	_ = tempFs.Remove(testFile)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	app := runtimepkg.NewApp(runtimepkg.Dependencies{
		DB:         db,
		Locker:     locker,
		Queue:      taskQueue,
		Subscriber: subscriber,
		FS:         vfs,
		TempFS:     tempFs,
	})
	moduleDeps := app.ModuleDeps()
	appCtx := moduleDeps.WithContext(ctx)
	common.StartEventLoop(appCtx)

	mmdbSources, _ := intrepo.ScanAllSources(appCtx)
	moduleOpts := moduleOptions{
		enableWorkflow:     common.Opts.Modules.Workflow,
		enableIntelligence: common.Opts.Modules.Intelligence,
	}
	modules := buildModules(moduleDeps, mmdbSources, moduleOpts)
	if err := registerModules(app, modules); err != nil {
		log.Fatalf("Failed to register core modules: %v", err)
	}
	if err := app.Start(appCtx); err != nil {
		log.Fatalf("Failed to start app modules: %v", err)
	}

	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.StripSlashes)
	r.Use(render.SetContentType(render.ContentTypeJSON))
	r.Use(func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			defer func() {
				if rvr := recover(); rvr != nil {
					if rvr == http.ErrAbortHandler {
						panic(rvr)
					}
					log.Printf("Panic: %v", rvr)
					common.InternalServerError(w, r, http.StatusInternalServerError, "Internal Server Error")
				}
			}()
			next.ServeHTTP(w, r)
		})
	})

	r.Group(func(r chi.Router) {
		r.Use(middleware.Logger)
		r.Route("/api/v1", func(r chi.Router) {
			app.RegisterRoutes(r)
		})
	})

	r.Get("/api/swagger", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/api/swagger/", http.StatusMovedPermanently)
	})
	r.Mount("/api/swagger", httpSwagger.Handler(
		httpSwagger.URL("/api/swagger/doc.json"),
	))

	if debug {
		target, _ := url.Parse("http://127.0.0.1:4200")
		proxy := httputil.NewSingleHostReverseProxy(target)
		r.NotFound(func(w http.ResponseWriter, r *http.Request) {
			if strings.HasPrefix(r.URL.Path, "/api/v1/") {
				common.Error(w, r, http.StatusNotFound, http.StatusNotFound, "API endpoint not found")
				return
			}
			proxy.ServeHTTP(w, r)
		})
	} else {
		staticFS, err := fs.Sub(assets.Static, "static")
		if err != nil {
			log.Fatal(err)
		}
		fileServer := http.FileServer(http.FS(staticFS))
		r.NotFound(func(w http.ResponseWriter, r *http.Request) {
			if strings.HasPrefix(r.URL.Path, "/api/v1/") {
				common.Error(w, r, http.StatusNotFound, http.StatusNotFound, "API endpoint not found")
				return
			}
			path := strings.TrimPrefix(r.URL.Path, "/")
			if path == "" {
				path = "index.html"
			}
			_, err := staticFS.Open(path)
			if err != nil {
				r.URL.Path = "/"
			}
			fileServer.ServeHTTP(w, r)
		})
	}

	srv := &http.Server{
		Addr:    common.Opts.Bind,
		Handler: r,
	}

	go func() {
		log.Printf("Server starting on %s", common.Opts.Bind)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("listen: %s\n", err)
		}
	}()

	<-ctx.Done()

	log.Println("Shutting down server...")
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := app.Stop(shutdownCtx); err != nil {
		log.Printf("App modules forced to stop with errors: %v", err)
	}
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("Server forced to shutdown: %v", err)
	}
	log.Println("Server exiting")
}
