package main

//go:generate swag init

import (
	"context"
	"errors"
	"flag"
	"homelab/assets"
	"homelab/pkg/common"
	"io/fs"
	"log"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	_ "homelab/docs" // This will be generated by swag
	_ "homelab/pkg/services/orchestration/processors"
	"homelab/pkg/services/orchestration"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger"
	"gopkg.d7z.net/middleware/kv"
	"gopkg.in/yaml.v3"
)

var (
	config string
	debug  bool
)

func init() {
	flag.StringVar(&config, "config", "", "config file")
	flag.BoolVar(&debug, "debug", false, "debug mode")
	flag.Parse()
}

// @title Homelab API
// @version 1.0
// @description This is a sample server for homelab.
// @BasePath /api/v1
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	if config != "" {
		if data, err := os.ReadFile(config); err == nil {
			if err = yaml.Unmarshal(data, common.Opts); err != nil {
				log.Fatal(err)
			}
		} else {
			log.Fatal("config file not exist")
		}
	}
	common.Opts.ParseEnv()
	db, err := kv.NewKVFromURL(common.Opts.DB)
	if err != nil {
		log.Fatal(err)
	}
	common.DB = db
	defer db.Close()

	orchestration.BootUpSelfHealing()

	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Logger)
	r.Use(func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			defer func() {
				if rvr := recover(); rvr != nil {
					if rvr == http.ErrAbortHandler {
						panic(rvr)
					}
					log.Printf("Panic: %v", rvr)
					common.InternalServerError(w, r, http.StatusInternalServerError, "Internal Server Error")
				}
			}()
			next.ServeHTTP(w, r)
		})
	})

	r.Group(func(r chi.Router) {
		Router(r)
	})
	r.Get("/api/swagger/*", httpSwagger.WrapHandler)
	if debug {
		log.Printf("Debug mode enabled, proxying frontend to http://127.0.0.1:4200")
		target, _ := url.Parse("http://127.0.0.1:4200")
		proxy := httputil.NewSingleHostReverseProxy(target)
		r.NotFound(func(w http.ResponseWriter, r *http.Request) {
			proxy.ServeHTTP(w, r)
		})
	} else {
		staticFS, err := fs.Sub(assets.Static, "static")
		if err != nil {
			log.Fatal(err)
		}
		fileServer := http.FileServer(http.FS(staticFS))
		r.NotFound(func(w http.ResponseWriter, r *http.Request) {
			path := strings.TrimPrefix(r.URL.Path, "/")
			if path == "" {
				path = "index.html"
			}
			_, err := staticFS.Open(path)
			if err != nil {
				r.URL.Path = "/"
			}
			fileServer.ServeHTTP(w, r)
		})
	}

	srv := &http.Server{
		Addr:    common.Opts.Bind,
		Handler: r,
	}

	go func() {
		log.Printf("Server starting on %s", common.Opts.Bind)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("listen: %s\n", err)
		}
	}()

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)

	<-stop

	log.Println("Shutting down server...")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := srv.Shutdown(ctx); err != nil {
		log.Printf("Server forced to shutdown: %v", err)
	}

	log.Println("Server exiting")
}
